apiVersion: cloudingress.managed.openshift.io/v1alpha1
kind: PublishingStrategy
metadata:
  name: example-publishingstrategy
spec:
  defaultAPIServerIngress:
    listening: internal
  applicationIngress:
    - listening: external
      default: true
      dnsName: "*.apps"
      certificate:
        secretRef:
          name: foo
          namespace: bar
      routeSelector:
        labelSelector:
          matchLabels:
            foo: bar